language: php

os:
  - linux
  - osx

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer update --no-interaction --prefer-source --dev
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - phpunit --bootstrap ./tests/bootstrap/autoload.php --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
